
spring:
    data:
        mongodb:
            uri: mongodb+srv://<username>:<password>@<cluster>mongodb.net/<dbname>?retryWrites=true&w=majority
            database: dbname
server:
    port: 8080


